### ISSUE TITLE
Update instructions to run tests

### ISSUE THREAD

**Issue by artoric** [minddust/jquery-pjaxr#38]
Hi Stephan,
I tried to run your examples and test locally, but somehow -following your instructions on the website- doesn't work:
```
$ git clone https://github.com/minddust/jquery-pjaxr.git
$ cd jquery-pjaxr/
$ python ./tests/app.py
$ phantomjs ./tests/run-qunit.js "http://localhost:5000/"
```
Flask and Phantomjs are installed.
Thank you!

**Comment by minddust** [comment]
hi @artoric 

sorry for the delay. the problem is that i'm just working in my spare time on these projects and that has been very rare due to other commitments. 

for your problem:

you missed the install part in the `.travis.yml`

but you are right. i will provide a proper test instruction. today is pjaxr day ;)

if there is anything else - feedback is always welcome.

cheers stephan

**Comment by minddust** [comment]
Added to readme.
